apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-chat
  labels:
    app: springboot-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-chat
  template:
    metadata:
      labels:
        app: springboot-chat
    spec:
      containers:
        - name: springboot-chat
          image: 192.168.0.147:30008/chat-spboot:v0.0.6
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '200m'
              memory: '256Mi'
          env:
            - name: CHAT_APP_PROFILE
              value: prod
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springboot-chat-secrets
                  key: MYSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: springboot-chat-config
