#service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.name }}-service
spec:
  selector:
    app: {{ .Chart.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP