#service
apiVersion: v1
kind: Service
metadata:
  name: springboot-chat-service
spec:
  selector:
    app: springboot-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP