oracle2:
  url: jdbc:mysql://192.168.0.135:30036/chat_db
  username: root
  driver: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL8Dialect
sso:
  url: http://localhost:8080/sso/verify-token
server:
  port: 8081

